/**
 * Hard-coded topology that mirrors the master data generated by
 * cloud/services/master-service/scripts/generate-complete-mockup-v2.js.
 *
 * We focus on three duck-meat customers, each with a flagship farm and
 * three grow-out houses. Device IDs follow the pattern created by the
 * master script so downstream services can cross-reference metadata.
 */
export const duckFarmTopology = [
  {
    tenantId: 'tenant_001',
    tenantName: 'บริษัท ฟาร์มเป็ดรุ่งเรือง จำกัด',
    farms: [
      {
        farmId: 'farm_tenant_001_001',
        farmName: 'ฟาร์มเป็ดรุ่งเรือง 1',
        houses: [
          {
            houseId: 'house_farm_tenant_001_001_001',
            houseName: 'โรงเรือน A',
            cameraId: 'cam_farm_tenant_001_001_001',
          },
          {
            houseId: 'house_farm_tenant_001_001_002',
            houseName: 'โรงเรือน B',
            cameraId: 'cam_farm_tenant_001_001_002',
          },
          {
            houseId: 'house_farm_tenant_001_001_003',
            houseName: 'โรงเรือน C',
            cameraId: 'cam_farm_tenant_001_001_003',
          },
        ],
      },
    ],
  },
  {
    tenantId: 'tenant_002',
    tenantName: 'สหกรณ์ผู้เลี้ยงเป็ดเนื้อรวมใจ',
    farms: [
      {
        farmId: 'farm_tenant_002_001',
        farmName: 'ฟาร์มรวมใจ 1',
        houses: [
          {
            houseId: 'house_farm_tenant_002_001_001',
            houseName: 'โรงเรือน A',
            cameraId: 'cam_farm_tenant_002_001_001',
          },
          {
            houseId: 'house_farm_tenant_002_001_002',
            houseName: 'โรงเรือน B',
            cameraId: 'cam_farm_tenant_002_001_002',
          },
          {
            houseId: 'house_farm_tenant_002_001_003',
            houseName: 'โรงเรือน C',
            cameraId: 'cam_farm_tenant_002_001_003',
          },
        ],
      },
    ],
  },
  {
    tenantId: 'tenant_003',
    tenantName: 'กลุ่มเกษตรกรฟาร์มเป็ดบางปะกง',
    farms: [
      {
        farmId: 'farm_tenant_003_001',
        farmName: 'ฟาร์มบางปะกง 1',
        houses: [
          {
            houseId: 'house_farm_tenant_003_001_001',
            houseName: 'โรงเรือน A',
            cameraId: 'cam_farm_tenant_003_001_001',
          },
          {
            houseId: 'house_farm_tenant_003_001_002',
            houseName: 'โรงเรือน B',
            cameraId: 'cam_farm_tenant_003_001_002',
          },
          {
            houseId: 'house_farm_tenant_003_001_003',
            houseName: 'โรงเรือน C',
            cameraId: 'cam_farm_tenant_003_001_003',
          },
        ],
      },
    ],
  },
];

export const deviceIdForHouse = (houseId) => `device_${houseId}_001`;
export const stationIdForHouse = (houseId) => `station_${houseId}_control`; // synthetic control-room station
